// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARyHaMULxWkET5GsoLNatlCoJC6Xnan4U',
    appId: '1:938423391335:web:24576a4166361d0d1230c2',
    messagingSenderId: '938423391335',
    projectId: 'trickcal-coupon-notifier',
    authDomain: 'trickcal-coupon-notifier.firebaseapp.com',
    storageBucket: 'trickcal-coupon-notifier.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl_jLGbFBIkwUqaFQ5XP6D4jRweVCzDEQ',
    appId: '1:938423391335:android:a23001c64105a3f71230c2',
    messagingSenderId: '938423391335',
    projectId: 'trickcal-coupon-notifier',
    storageBucket: 'trickcal-coupon-notifier.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU9LW7ER9ZT8Fz97mTb7baevzQaGjB5S0',
    appId: '1:938423391335:ios:3a41de6bda17eb991230c2',
    messagingSenderId: '938423391335',
    projectId: 'trickcal-coupon-notifier',
    storageBucket: 'trickcal-coupon-notifier.firebasestorage.app',
    iosBundleId: 'io.trickcal.trickcalCouponNotifier',
  );
}
